from django.conf.urls import patterns, include, url

from django.contrib import admin

from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'erunner.views_auth.login_view', name='login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', 'erunner.views_auth.login_view'),
    #url(r'^login/', 'django.contrib.auth.views.login', {'template_name':'login.html'}),
    url(r'^logout/', 'erunner.views_auth.logout_view'),
    url(r'^execute/','erunner.views_execute.execute'),
    url(r'^mainframe/','erunner.views_mainframe.mainframe'),
    url(r'^showlog/', 'erunner.view_show.showlog'),
    url(r'^showcode', 'erunner.views_code.showcode'),
    url(r'^report/','erunner.views_report.report'),
    url(r'^result/(?P<JobID>)','erunner.views_result.result'),
    url(r'^analysis/', 'erunner.views_analysis.analysis'),
    url(r'^tools/', 'erunner.views_tools.tools'),
    url(r'^editFile/', 'erunner.views_tools.editFile'),
    url(r'^updateFile/', 'erunner.views_tools.updateFile'),
    url(r'^deleteFile/', 'erunner.views_tools.deleteFile'),
    url(r'^system/', 'erunner.views_system.sysMgt'),
    url(r'^configure/', 'erunner.views_configure.configure'),
    url(r'AddRunSuite/', 'erunner.views_configure.AddRunSuite'),
    url(r'CheckSuiteName/', 'erunner.views_configure.CheckSuiteName'),
    url(r'ConfigUpdateVersion/', 'erunner.views_configure.ConfigUpdateVersion'),
    url(r'ConfigUpdateSuite/', 'erunner.views_configure.ConfigUpdateSuite'),
    url(r'EditJob/', 'erunner.views_execute.EditJob'),
    url(r'UpdateProduct/', 'erunner.views_execute.UpdateProduct'),
    url(r'UpdateModule/', 'erunner.views_execute.UpdateModule'),
    url(r'UpdateVersion/', 'erunner.views_execute.UpdateVersion'),
    url(r'InsertJob/', 'erunner.views_execute.InsertJob'),
    url(r'CheckJobName/', 'erunner.views_execute.CheckJobName'),
    url(r'FilterJob/', 'erunner.views_execute.FilterJob'),
    url(r'ChangeJobStatus/', 'erunner.views_execute.ChangedJobStatus'),
    url(r'DeleteJob/', 'erunner.views_execute.DeleteJob'),
    url(r'UpdateJob/', 'erunner.views_execute.UpdateJob'),
    url(r'RunJob/', 'erunner.views_process.RunJob'),
    url(r'FileChangedHandled/', 'erunner.views_process.FileChangedHandled'),
    url(r'PostTestResult/', 'erunner.views_process.PostTestResult'),
    url(r'ReportProductChanged/', 'erunner.views_report.ReportProductChanged'),
    url(r'ReportModuleChanged/', 'erunner.views_report.ReportModuleChanged'),
    url(r'ReportJobChanged/', 'erunner.views_report.ReportJobChanged'),
    url(r'SearchResult/', 'erunner.views_result.SearchResult'),
    url(r'SearchFailedResult/', 'erunner.views_result.SearchFailedResult'),
    url(r'SearchPassedResult/', 'erunner.views_result.SearchPassedResult'),
    url(r'LoadDetailResult/', 'erunner.views_result.LoadDetailResult'),
    url(r'LoadDetailCode/', 'erunner.views_result.LoadDetailCode'),
    url(r'AddProduct/', 'erunner.views_execute.AddProduct'),
)
